server:
  port: 9803
spring:
  data: 
    neo4j:
      username: neo4j
      password: neo4j@wankeauto.com
      uri: http://39.108.124.91:8068
  redis:
    database: 0
    host: 39.108.124.91
    port: 8067
    password: Jhf&*d93jfdKJSf
    pool:
      max-active: 400
      max-wait: 10000
      max-idle: 100
      min-idle: 0
    timeout: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.108.124.91:8046/sgool4?useUnicode=true&characterEncoding=utf-8&serverTimezone=CTT
    username: wanke
    password: 5j1#H!^d
    driverClassName: com.mysql.cj.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4jlo
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    database: mysql 
hbase:
  zookeeper:
    quorum: 192.168.2.32
    property:
      clientPort: 2181
  rootdir: hdfs://192.168.2.32:9000/hbase
  client:
    keyvalue:
      maxsize: 500000
tsdb: 
  url: 192.168.2.13
kafka:
  bootstrap-servers: 192.168.2.222:9092
    group-id: myGroup  
