server:
  port: 8901
spring:
  data: 
    neo4j:
      username: neo4j
      password: neo4j@wankeauto.com
      uri: http://192.168.2.116:7475
  kafka:
    bootstrap-servers: 192.168.2.32:9092,192.168.2.33:9092,192.168.2.34:9092
    group-id: myGroup
    consumer:
      group-id: consumer-group
  redis:
    database: 0
    host: 192.168.2.13
    port: 8811
    password: Jhf&*d93jfdKJSf
    pool:
      max-active: 400
      max-wait: 10000
      max-idle: 100
      min-idle: 0
    timeout: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.2.13:3306/sgool4?useUnicode=true&characterEncoding=utf-8
    username: wanke
    password: 5j1#H!^d
    driverClassName: com.mysql.jdbc.Driver
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  jpa:
    database: mysql 
hystrix:
  threadpool:
    default:
      #并发执行的最大线程数，默认10
      coreSize: 500
      maximumSize: 500
      allowMaximumSizeToDivergeFromCoreSize: true
      #最大队列数量
      maxQueueSize: -1
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
  command:
    default:
      execution:
        timeout:
          #如果enabled设置为false，则请求超时交给ribbon控制,为true,则超时作为熔断根据
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000
ribbon:
  #服务配置serviceId方式时，以下超时规则生效
  ReadTimeout: 50000
  ConnectTimeout: 50000
  eureka:
    enabled: true
